---
title: "SMAC Results"
author: "Yuri Lavinas"
date: "4/16/2017"
output:
  pdf_document:
    fig_caption: yes
    toc: yes
  html_document: default
  word_document: default
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(cache=TRUE)
```

#Summary
In this document we show the convergency plots for the GAModel and ReducedGAmodel with tournize size (k) 3 and tournsize (k) 2. The value of k being 2 was select by SMAC after it was executed for 2 days for both models. 

```{r setup, include=FALSE}
library(knitr)
library(ggplot2)
library(gridExtra)
opts_chunk$set(dev='pdf')
#functions needed to create convergency plots

#this function loads data e do a little of data arrangements
loadData = function(type,region, year, i){
    setwd("~/Documents/estudos/master-unb/earthquakemodels/Zona4/")
    file = paste(type,'/',region, type,year,'_',i,'logbook.txt',sep="")
    data = read.csv2(file, sep='\t', header=T)
    data$std = as.numeric(levels(data$std))[data$std]
    data$max = as.numeric(levels(data$max))[data$max]   
    return(data)
}

#this functions selects a region given a number from 1 to 4
chooseRegion = function(i){
    if (i==1) {
        region="Kanto"
    }
    else if (i==2) {
        region="Kansai"
    }
    else if (i==3) {
        region = "Tohoku"
    }
    else{
        region = "EastJapan"
    }
    return(region)
}

#this function loads the data from the files contating loglikehood values from exps:
    # with and without smac optmizatiom
createData = function(modelName, region, year){
    
    data1 = loadData(modelName, region, year, 0)
    data2 = loadData(modelName, region, year, 1)
    data3 = loadData(modelName, region, year, 2)
    data4 = loadData(modelName, region, year, 3)
    data5 = loadData(modelName, region, year, 4)
    data6 = loadData(modelName, region, year, 5)
    data7 = loadData(modelName, region, year, 6)
    data8 = loadData(modelName, region, year, 7)
    data9 = loadData(modelName, region, year, 8)
    data10 = loadData(modelName, region, year, 9)
    
    data1$std = pmin(data1$std, 500)
    data2$std = pmin(data1$std, 500)
    data3$std = pmin(data1$std, 500)
    data4$std = pmin(data1$std, 500)
    data5$std = pmin(data1$std, 500)
    data6$std = pmin(data1$std, 500)
    data7$std = pmin(data1$std, 500)
    data8$std = pmin(data1$std, 500)
    data9$std = pmin(data1$std, 500)
    data10$std = pmin(data1$std, 500)
    
    maxs = c(rep(0,length(data1$max)))
    for (i in 1:length(data1$max)){
        maxs[i] = ((data1$max[i] + data2$max[i] + data3$max[i] + data4$max[i] + data5$max[i] + 
                        data6$max[i] + data7$max[i] + data8$max[i] + data9$max[i] + data10$max[i])/10)
    }
    
    stds = c(rep(0,length(data1$std)))
    for (i in 1:length(data1$std)){
        stds[i] = ((data1$std[i] + data2$std[i] + data3$std[i] + data4$std[i] + data5$std[i] + 
                        data6$std[i] + data7$std[i] + data8$std[i] + data9$std[i] + data10$std[i])/10)
    }
    
    gen = c(1:100)
    data = data.frame(
        setNames(replicate(3,numeric(0), simplify = F),
                 c("maxs", "stds", "gen")))
    
    data = data.frame(maxs, stds, gen)
    
    return (data)
}

# this functions creates the convergency plots
plotConvergencyData = function(data1, data2, data3, data4, type, region, year){
        p1<- ggplot(data1, aes(x=gen, y=maxs), group=maxs) + 
            geom_line(color='orange') +
            geom_point(color='orange')+
            geom_step(data = data2, color='blue')

        p2<- ggplot(data3, aes(x=gen, y=maxs), group=maxs) + 
            geom_line(color='orange') +
            geom_point(color='orange')+
            geom_step(data = data4, color='blue')
    
        grid.arrange(p1+ggtitle(paste(region, year, "GAModel (Orange, k=3, Blue k=2)"))+
            theme(axis.text=element_text(size=14))+
            theme(plot.title = element_text(face="bold")), 
                 p2+ggtitle(paste(region,year, "ReducedGAModel (Orange, k=3, Blue k=2)"))+
            theme(axis.text=element_text(size=14))+
            theme(plot.title = element_text(face="bold"))
    , nrow=2) 
}
```

## Convergency plots
 

```{r, echo=FALSE}

for (i in 1:4){
    region = chooseRegion(i)
    for (year in 2005:2010){
        tournizeRegion = paste('tournsize=2',region,sep="")
        data1=createData(modelName='GAModel',region,year)
        data2=createData(modelName='GAModel',tournizeRegion,year)
        # plotConvergencyData(data1, data2,'GAModel', region, year)
        data3=createData(modelName='ReducedGAModel',region,year)
        data4=createData(modelName='ReducedGAModel',tournizeRegion,year)
        plotConvergencyData(data1, data2, data3, data4,'ReducedGAModel', region, year)
    
    }    
}

```

 


```{r, echo=FALSE}

#convert data from file to  numeric type and removes parenthesis
convertToNumeric = function(model){
        aux=gsub(".*\\((.*)\\).*", "\\1", model$V1)
        aux=gsub(",", "\\1", aux)
        values = as.numeric(aux)
    # }
    return(values)
}

#load loglikehood data files
loadDataLoglikelihood = function(type, region, year, prefix){
    setwd("~/Documents/estudos/master-unb/earthquakemodels/Zona4/")
    file = paste(type,'/',prefix,region,type,year,"_loglikelihood.txt",sep="")
    data = read.csv2(file, sep='\n', header=F)
    return(data)
}


#this fucntion creates a dataframe from with loglikehood valus
createDataFrame4AOV = function(modelName){
    finalData = data.frame(
        setNames(replicate(4,numeric(0), simplify = F),
                 c("loglikeValues", "model", "years", "regions")))
    
    for (i in 1:4) {
        region = chooseRegion(i)    
        for (year in 2000:2005) {
            
            prefix = ''
            ga = loadDataLoglikelihood(modelName, region, year+5, prefix)
            prefix = 'tournsize=2'
            tournsize2 = loadDataLoglikelihood(modelName,region, year+5, prefix)
            
            loglike = convertToNumeric(ga)
            logliketournsize2 = convertToNumeric(tournsize2)
            loglikeValues = c(loglike, logliketournsize2)
            
            nameGA = c(rep(modelName,10))
            name=paste(modelName, 'tournsize2',sep='')
            nameLista = c(rep(name,10))
            
            years = c(rep(toString(year+5),20))
            regions = c(rep(region, 20))
            model = c(nameGA, nameLista)
            data = data.frame(loglikeValues, model, years, regions)
            if (dim(finalData)[1]==0) {
                finalData = merge(finalData, data, all.y=T)  
            }
            else{
                finalData=rbind(finalData, data)
            }
        }
    }    
    return(finalData)
}

data = createDataFrame4AOV('GAModel')
```

#ANOVA test and HSD Tukey
##All regions

```{r}
resultANOVA = aov(loglikeValues~model+years+regions, data = data)
summary(resultANOVA)
tuk = TukeyHSD(resultANOVA)
op <- par(mar = c(5,14,4,2)+0.1)
plot(tuk,las=0)
```


##KANTO
```{r}

subTabela = data[data$regions=="Kanto",]
print("In Kanto")
resultANOVA = aov(loglikeValues~model+years, data = subTabela)
summary(resultANOVA)
tuk = TukeyHSD(resultANOVA)
op <- par(mar = c(5,14,4,2)+0.1)
plot(tuk,las=0)
```

##EASTJAPAN
```{r}

subTabela2 = data[data$regions=="EastJapan",]
print("In EastJapan")
resultANOVA = aov(loglikeValues~model+years, data = subTabela2)
summary(resultANOVA)
tuk = TukeyHSD(resultANOVA)
op <- par(mar = c(5,14,4,2)+0.1)
plot(tuk,las=0)
```

```{R}
subTabela3 = data[data$regions=="Kansai",]
print("In Kansai")
resultANOVA = aov(loglikeValues~model+years, data = subTabela3)
summary(resultANOVA)
tuk = TukeyHSD(resultANOVA)
op <- par(mar = c(5,14,4,2)+0.1)
plot(tuk,las=0)

```

##TOHOKU

```{R}
subTabela3 = data[data$regions=="Tohoku",]
print("In Tohoku")
resultANOVA = aov(loglikeValues~model+years, data = subTabela3)
summary(resultANOVA)
tuk = TukeyHSD(resultANOVA)
op <- par(mar = c(5,14,4,2)+0.1)
plot(tuk,las=0)
```



```{r, include=FALSE}
# ttestPaired= function(region){
#     subTabela6 = subTabela[subTabela$regions==region,]
#     aggfinaldata<-aggregate(loglikeValues~years:model, data=subTabela6,FUN=mean)
#     # Perform paired t-test
#     cat('in', region, 'the t.test between the models GAModelSC and ReducedGAModelSC is: ')
#     difTimes<-with(aggfinaldata,loglikeValues[1:6]-loglikeValues[7:12])
#     print(t.test(difTimes))
#     cat('in', region, 'the t.test between the models GAModelSC and Emp-GAModelSC is: ')
#     difTimes<-with(aggfinaldata,loglikeValues[1:6]-loglikeValues[13:18])
#     print(t.test(difTimes))
#     cat('in', region, 'the t.test between the models ReducedGAModelSC and Emp-GAModelSC is: ')
#     difTimes<-with(aggfinaldata,loglikeValues[7:12]-loglikeValues[13:18])
#     print(t.test(difTimes))
# }


```

